// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: key_curator.proto

package key_curator

import (
	proto "github.com/etclab/rbe/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_key_curator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_key_curator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_key_curator_proto_rawDescGZIP(), []int{0}
}

type PublicParamsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pp            *proto.PublicParams    `protobuf:"bytes,1,opt,name=pp,proto3" json:"pp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicParamsResponse) Reset() {
	*x = PublicParamsResponse{}
	mi := &file_key_curator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicParamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicParamsResponse) ProtoMessage() {}

func (x *PublicParamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_key_curator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicParamsResponse.ProtoReflect.Descriptor instead.
func (*PublicParamsResponse) Descriptor() ([]byte, []int) {
	return file_key_curator_proto_rawDescGZIP(), []int{1}
}

func (x *PublicParamsResponse) GetPp() *proto.PublicParams {
	if x != nil {
		return x.Pp
	}
	return nil
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PublicKey     *proto.G1              `protobuf:"bytes,2,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	Xi            []*proto.G1            `protobuf:"bytes,3,rep,name=xi,proto3" json:"xi,omitempty"`
	Ip            string                 `protobuf:"bytes,4,opt,name=ip,proto3" json:"ip,omitempty"`
	Port          string                 `protobuf:"bytes,5,opt,name=port,proto3" json:"port,omitempty"`
	Token         string                 `protobuf:"bytes,6,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_key_curator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_key_curator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_key_curator_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RegisterRequest) GetPublicKey() *proto.G1 {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *RegisterRequest) GetXi() []*proto.G1 {
	if x != nil {
		return x.Xi
	}
	return nil
}

func (x *RegisterRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *RegisterRequest) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *RegisterRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type UserOpeningResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Commitments        []*proto.G1            `protobuf:"bytes,1,rep,name=commitments,proto3" json:"commitments,omitempty"`
	Opening            []*proto.G1            `protobuf:"bytes,2,rep,name=opening,proto3" json:"opening,omitempty"`
	CounterAttestation *CounterAttestation    `protobuf:"bytes,3,opt,name=counterAttestation,proto3" json:"counterAttestation,omitempty"` // TODO: add membership proof here
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UserOpeningResponse) Reset() {
	*x = UserOpeningResponse{}
	mi := &file_key_curator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserOpeningResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserOpeningResponse) ProtoMessage() {}

func (x *UserOpeningResponse) ProtoReflect() protoreflect.Message {
	mi := &file_key_curator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserOpeningResponse.ProtoReflect.Descriptor instead.
func (*UserOpeningResponse) Descriptor() ([]byte, []int) {
	return file_key_curator_proto_rawDescGZIP(), []int{3}
}

func (x *UserOpeningResponse) GetCommitments() []*proto.G1 {
	if x != nil {
		return x.Commitments
	}
	return nil
}

func (x *UserOpeningResponse) GetOpening() []*proto.G1 {
	if x != nil {
		return x.Opening
	}
	return nil
}

func (x *UserOpeningResponse) GetCounterAttestation() *CounterAttestation {
	if x != nil {
		return x.CounterAttestation
	}
	return nil
}

type UpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_key_curator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_key_curator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_key_curator_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Opening struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Opening       []*proto.G1            `protobuf:"bytes,1,rep,name=opening,proto3" json:"opening,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Opening) Reset() {
	*x = Opening{}
	mi := &file_key_curator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Opening) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Opening) ProtoMessage() {}

func (x *Opening) ProtoReflect() protoreflect.Message {
	mi := &file_key_curator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Opening.ProtoReflect.Descriptor instead.
func (*Opening) Descriptor() ([]byte, []int) {
	return file_key_curator_proto_rawDescGZIP(), []int{5}
}

func (x *Opening) GetOpening() []*proto.G1 {
	if x != nil {
		return x.Opening
	}
	return nil
}

type AllUpdatesResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AllCommitments []*proto.G1            `protobuf:"bytes,1,rep,name=allCommitments,proto3" json:"allCommitments,omitempty"`
	AllOpenings    []*Opening             `protobuf:"bytes,2,rep,name=allOpenings,proto3" json:"allOpenings,omitempty"`
	History        []*RegistrationEvent   `protobuf:"bytes,3,rep,name=history,proto3" json:"history,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AllUpdatesResponse) Reset() {
	*x = AllUpdatesResponse{}
	mi := &file_key_curator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllUpdatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllUpdatesResponse) ProtoMessage() {}

func (x *AllUpdatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_key_curator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllUpdatesResponse.ProtoReflect.Descriptor instead.
func (*AllUpdatesResponse) Descriptor() ([]byte, []int) {
	return file_key_curator_proto_rawDescGZIP(), []int{6}
}

func (x *AllUpdatesResponse) GetAllCommitments() []*proto.G1 {
	if x != nil {
		return x.AllCommitments
	}
	return nil
}

func (x *AllUpdatesResponse) GetAllOpenings() []*Opening {
	if x != nil {
		return x.AllOpenings
	}
	return nil
}

func (x *AllUpdatesResponse) GetHistory() []*RegistrationEvent {
	if x != nil {
		return x.History
	}
	return nil
}

type RegistrationEvent struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Token              string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Ip                 string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Port               string                 `protobuf:"bytes,3,opt,name=port,proto3" json:"port,omitempty"`
	Id                 int32                  `protobuf:"varint,4,opt,name=id,proto3" json:"id,omitempty"`
	PublicKey          *proto.G1              `protobuf:"bytes,5,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	Xi                 []*proto.G1            `protobuf:"bytes,6,rep,name=xi,proto3" json:"xi,omitempty"`
	Request            *RegisterRequest       `protobuf:"bytes,7,opt,name=request,proto3" json:"request,omitempty"`
	CounterAttestation *CounterAttestation    `protobuf:"bytes,8,opt,name=counterAttestation,proto3" json:"counterAttestation,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RegistrationEvent) Reset() {
	*x = RegistrationEvent{}
	mi := &file_key_curator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationEvent) ProtoMessage() {}

func (x *RegistrationEvent) ProtoReflect() protoreflect.Message {
	mi := &file_key_curator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationEvent.ProtoReflect.Descriptor instead.
func (*RegistrationEvent) Descriptor() ([]byte, []int) {
	return file_key_curator_proto_rawDescGZIP(), []int{7}
}

func (x *RegistrationEvent) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RegistrationEvent) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *RegistrationEvent) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *RegistrationEvent) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RegistrationEvent) GetPublicKey() *proto.G1 {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *RegistrationEvent) GetXi() []*proto.G1 {
	if x != nil {
		return x.Xi
	}
	return nil
}

func (x *RegistrationEvent) GetRequest() *RegisterRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *RegistrationEvent) GetCounterAttestation() *CounterAttestation {
	if x != nil {
		return x.CounterAttestation
	}
	return nil
}

type CounterAttestation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Counter       uint64                 `protobuf:"varint,1,opt,name=counter,proto3" json:"counter,omitempty"`
	MsgHash       []byte                 `protobuf:"bytes,2,opt,name=msgHash,proto3" json:"msgHash,omitempty"`
	Signature     *ECDSASignature        `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CounterAttestation) Reset() {
	*x = CounterAttestation{}
	mi := &file_key_curator_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CounterAttestation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CounterAttestation) ProtoMessage() {}

func (x *CounterAttestation) ProtoReflect() protoreflect.Message {
	mi := &file_key_curator_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CounterAttestation.ProtoReflect.Descriptor instead.
func (*CounterAttestation) Descriptor() ([]byte, []int) {
	return file_key_curator_proto_rawDescGZIP(), []int{8}
}

func (x *CounterAttestation) GetCounter() uint64 {
	if x != nil {
		return x.Counter
	}
	return 0
}

func (x *CounterAttestation) GetMsgHash() []byte {
	if x != nil {
		return x.MsgHash
	}
	return nil
}

func (x *CounterAttestation) GetSignature() *ECDSASignature {
	if x != nil {
		return x.Signature
	}
	return nil
}

type ECDSASignature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	R             []byte                 `protobuf:"bytes,1,opt,name=r,proto3" json:"r,omitempty"`
	S             []byte                 `protobuf:"bytes,2,opt,name=s,proto3" json:"s,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ECDSASignature) Reset() {
	*x = ECDSASignature{}
	mi := &file_key_curator_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ECDSASignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECDSASignature) ProtoMessage() {}

func (x *ECDSASignature) ProtoReflect() protoreflect.Message {
	mi := &file_key_curator_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECDSASignature.ProtoReflect.Descriptor instead.
func (*ECDSASignature) Descriptor() ([]byte, []int) {
	return file_key_curator_proto_rawDescGZIP(), []int{9}
}

func (x *ECDSASignature) GetR() []byte {
	if x != nil {
		return x.R
	}
	return nil
}

func (x *ECDSASignature) GetS() []byte {
	if x != nil {
		return x.S
	}
	return nil
}

var File_key_curator_proto protoreflect.FileDescriptor

const file_key_curator_proto_rawDesc = "" +
	"\n" +
	"\x11key_curator.proto\x12\n" +
	"keycurator\x1a\trbe.proto\x1a\x1bgoogle/protobuf/empty.proto\"\a\n" +
	"\x05Empty\"?\n" +
	"\x14PublicParamsResponse\x12'\n" +
	"\x02pp\x18\x01 \x01(\v2\x17.rbe.proto.PublicParamsR\x02pp\"\xa7\x01\n" +
	"\x0fRegisterRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12+\n" +
	"\tpublicKey\x18\x02 \x01(\v2\r.rbe.proto.G1R\tpublicKey\x12\x1d\n" +
	"\x02xi\x18\x03 \x03(\v2\r.rbe.proto.G1R\x02xi\x12\x0e\n" +
	"\x02ip\x18\x04 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x05 \x01(\tR\x04port\x12\x14\n" +
	"\x05token\x18\x06 \x01(\tR\x05token\"\xbf\x01\n" +
	"\x13UserOpeningResponse\x12/\n" +
	"\vcommitments\x18\x01 \x03(\v2\r.rbe.proto.G1R\vcommitments\x12'\n" +
	"\aopening\x18\x02 \x03(\v2\r.rbe.proto.G1R\aopening\x12N\n" +
	"\x12counterAttestation\x18\x03 \x01(\v2\x1e.keycurator.CounterAttestationR\x12counterAttestation\"\x1f\n" +
	"\rUpdateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"2\n" +
	"\aOpening\x12'\n" +
	"\aopening\x18\x01 \x03(\v2\r.rbe.proto.G1R\aopening\"\xbb\x01\n" +
	"\x12AllUpdatesResponse\x125\n" +
	"\x0eallCommitments\x18\x01 \x03(\v2\r.rbe.proto.G1R\x0eallCommitments\x125\n" +
	"\vallOpenings\x18\x02 \x03(\v2\x13.keycurator.OpeningR\vallOpenings\x127\n" +
	"\ahistory\x18\x03 \x03(\v2\x1d.keycurator.RegistrationEventR\ahistory\"\xb0\x02\n" +
	"\x11RegistrationEvent\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x03 \x01(\tR\x04port\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\x05R\x02id\x12+\n" +
	"\tpublicKey\x18\x05 \x01(\v2\r.rbe.proto.G1R\tpublicKey\x12\x1d\n" +
	"\x02xi\x18\x06 \x03(\v2\r.rbe.proto.G1R\x02xi\x125\n" +
	"\arequest\x18\a \x01(\v2\x1b.keycurator.RegisterRequestR\arequest\x12N\n" +
	"\x12counterAttestation\x18\b \x01(\v2\x1e.keycurator.CounterAttestationR\x12counterAttestation\"\x82\x01\n" +
	"\x12CounterAttestation\x12\x18\n" +
	"\acounter\x18\x01 \x01(\x04R\acounter\x12\x18\n" +
	"\amsgHash\x18\x02 \x01(\fR\amsgHash\x128\n" +
	"\tsignature\x18\x03 \x01(\v2\x1a.keycurator.ECDSASignatureR\tsignature\",\n" +
	"\x0eECDSASignature\x12\f\n" +
	"\x01r\x18\x01 \x01(\fR\x01r\x12\f\n" +
	"\x01s\x18\x02 \x01(\fR\x01s2\xc7\x02\n" +
	"\n" +
	"KeyCurator\x12K\n" +
	"\vFetchUpdate\x12\x19.keycurator.UpdateRequest\x1a\x1f.keycurator.UserOpeningResponse\"\x00\x12K\n" +
	"\x0fFetchAllUpdates\x12\x16.google.protobuf.Empty\x1a\x1e.keycurator.AllUpdatesResponse\"\x00\x12O\n" +
	"\x11FetchPublicParams\x12\x16.google.protobuf.Empty\x1a .keycurator.PublicParamsResponse\"\x00\x12N\n" +
	"\fRegisterUser\x12\x1b.keycurator.RegisterRequest\x1a\x1f.keycurator.UserOpeningResponse\"\x00B5Z3istio.io/istio/security/pkg/key-curator/key-curatorb\x06proto3"

var (
	file_key_curator_proto_rawDescOnce sync.Once
	file_key_curator_proto_rawDescData []byte
)

func file_key_curator_proto_rawDescGZIP() []byte {
	file_key_curator_proto_rawDescOnce.Do(func() {
		file_key_curator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_key_curator_proto_rawDesc), len(file_key_curator_proto_rawDesc)))
	})
	return file_key_curator_proto_rawDescData
}

var file_key_curator_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_key_curator_proto_goTypes = []any{
	(*Empty)(nil),                // 0: keycurator.Empty
	(*PublicParamsResponse)(nil), // 1: keycurator.PublicParamsResponse
	(*RegisterRequest)(nil),      // 2: keycurator.RegisterRequest
	(*UserOpeningResponse)(nil),  // 3: keycurator.UserOpeningResponse
	(*UpdateRequest)(nil),        // 4: keycurator.UpdateRequest
	(*Opening)(nil),              // 5: keycurator.Opening
	(*AllUpdatesResponse)(nil),   // 6: keycurator.AllUpdatesResponse
	(*RegistrationEvent)(nil),    // 7: keycurator.RegistrationEvent
	(*CounterAttestation)(nil),   // 8: keycurator.CounterAttestation
	(*ECDSASignature)(nil),       // 9: keycurator.ECDSASignature
	(*proto.PublicParams)(nil),   // 10: rbe.proto.PublicParams
	(*proto.G1)(nil),             // 11: rbe.proto.G1
	(*empty.Empty)(nil),          // 12: google.protobuf.Empty
}
var file_key_curator_proto_depIdxs = []int32{
	10, // 0: keycurator.PublicParamsResponse.pp:type_name -> rbe.proto.PublicParams
	11, // 1: keycurator.RegisterRequest.publicKey:type_name -> rbe.proto.G1
	11, // 2: keycurator.RegisterRequest.xi:type_name -> rbe.proto.G1
	11, // 3: keycurator.UserOpeningResponse.commitments:type_name -> rbe.proto.G1
	11, // 4: keycurator.UserOpeningResponse.opening:type_name -> rbe.proto.G1
	8,  // 5: keycurator.UserOpeningResponse.counterAttestation:type_name -> keycurator.CounterAttestation
	11, // 6: keycurator.Opening.opening:type_name -> rbe.proto.G1
	11, // 7: keycurator.AllUpdatesResponse.allCommitments:type_name -> rbe.proto.G1
	5,  // 8: keycurator.AllUpdatesResponse.allOpenings:type_name -> keycurator.Opening
	7,  // 9: keycurator.AllUpdatesResponse.history:type_name -> keycurator.RegistrationEvent
	11, // 10: keycurator.RegistrationEvent.publicKey:type_name -> rbe.proto.G1
	11, // 11: keycurator.RegistrationEvent.xi:type_name -> rbe.proto.G1
	2,  // 12: keycurator.RegistrationEvent.request:type_name -> keycurator.RegisterRequest
	8,  // 13: keycurator.RegistrationEvent.counterAttestation:type_name -> keycurator.CounterAttestation
	9,  // 14: keycurator.CounterAttestation.signature:type_name -> keycurator.ECDSASignature
	4,  // 15: keycurator.KeyCurator.FetchUpdate:input_type -> keycurator.UpdateRequest
	12, // 16: keycurator.KeyCurator.FetchAllUpdates:input_type -> google.protobuf.Empty
	12, // 17: keycurator.KeyCurator.FetchPublicParams:input_type -> google.protobuf.Empty
	2,  // 18: keycurator.KeyCurator.RegisterUser:input_type -> keycurator.RegisterRequest
	3,  // 19: keycurator.KeyCurator.FetchUpdate:output_type -> keycurator.UserOpeningResponse
	6,  // 20: keycurator.KeyCurator.FetchAllUpdates:output_type -> keycurator.AllUpdatesResponse
	1,  // 21: keycurator.KeyCurator.FetchPublicParams:output_type -> keycurator.PublicParamsResponse
	3,  // 22: keycurator.KeyCurator.RegisterUser:output_type -> keycurator.UserOpeningResponse
	19, // [19:23] is the sub-list for method output_type
	15, // [15:19] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_key_curator_proto_init() }
func file_key_curator_proto_init() {
	if File_key_curator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_key_curator_proto_rawDesc), len(file_key_curator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_key_curator_proto_goTypes,
		DependencyIndexes: file_key_curator_proto_depIdxs,
		MessageInfos:      file_key_curator_proto_msgTypes,
	}.Build()
	File_key_curator_proto = out.File
	file_key_curator_proto_goTypes = nil
	file_key_curator_proto_depIdxs = nil
}
