// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.21.12
// source: key_curator.proto

package key_curator

import (
	proto "github.com/etclab/rbe/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReadyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Prefix string `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
}

func (x *ReadyRequest) Reset() {
	*x = ReadyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_key_curator_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadyRequest) ProtoMessage() {}

func (x *ReadyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_key_curator_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadyRequest.ProtoReflect.Descriptor instead.
func (*ReadyRequest) Descriptor() ([]byte, []int) {
	return file_key_curator_proto_rawDescGZIP(), []int{0}
}

func (x *ReadyRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ReadyRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_key_curator_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_key_curator_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_key_curator_proto_rawDescGZIP(), []int{1}
}

type PublicParamsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pp *proto.PublicParams `protobuf:"bytes,1,opt,name=pp,proto3" json:"pp,omitempty"`
}

func (x *PublicParamsResponse) Reset() {
	*x = PublicParamsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_key_curator_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublicParamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicParamsResponse) ProtoMessage() {}

func (x *PublicParamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_key_curator_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicParamsResponse.ProtoReflect.Descriptor instead.
func (*PublicParamsResponse) Descriptor() ([]byte, []int) {
	return file_key_curator_proto_rawDescGZIP(), []int{2}
}

func (x *PublicParamsResponse) GetPp() *proto.PublicParams {
	if x != nil {
		return x.Pp
	}
	return nil
}

type RegisterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int64       `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PublicKey *proto.G1   `protobuf:"bytes,2,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	Xi        []*proto.G1 `protobuf:"bytes,3,rep,name=xi,proto3" json:"xi,omitempty"`
	Ip        string      `protobuf:"bytes,4,opt,name=ip,proto3" json:"ip,omitempty"`
	Port      string      `protobuf:"bytes,5,opt,name=port,proto3" json:"port,omitempty"`
	Token     string      `protobuf:"bytes,6,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_key_curator_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_key_curator_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_key_curator_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RegisterRequest) GetPublicKey() *proto.G1 {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *RegisterRequest) GetXi() []*proto.G1 {
	if x != nil {
		return x.Xi
	}
	return nil
}

func (x *RegisterRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *RegisterRequest) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *RegisterRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type UserOpeningResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Commitment         *proto.G1           `protobuf:"bytes,1,opt,name=commitment,proto3" json:"commitment,omitempty"`
	Opening            []*proto.G1         `protobuf:"bytes,2,rep,name=opening,proto3" json:"opening,omitempty"`
	CounterAttestation *CounterAttestation `protobuf:"bytes,3,opt,name=counterAttestation,proto3" json:"counterAttestation,omitempty"`
	Proof              *proto.G1           `protobuf:"bytes,4,opt,name=proof,proto3" json:"proof,omitempty"`
	UsersBeforeMe      []int64             `protobuf:"varint,5,rep,packed,name=usersBeforeMe,proto3" json:"usersBeforeMe,omitempty"`
}

func (x *UserOpeningResponse) Reset() {
	*x = UserOpeningResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_key_curator_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserOpeningResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserOpeningResponse) ProtoMessage() {}

func (x *UserOpeningResponse) ProtoReflect() protoreflect.Message {
	mi := &file_key_curator_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserOpeningResponse.ProtoReflect.Descriptor instead.
func (*UserOpeningResponse) Descriptor() ([]byte, []int) {
	return file_key_curator_proto_rawDescGZIP(), []int{4}
}

func (x *UserOpeningResponse) GetCommitment() *proto.G1 {
	if x != nil {
		return x.Commitment
	}
	return nil
}

func (x *UserOpeningResponse) GetOpening() []*proto.G1 {
	if x != nil {
		return x.Opening
	}
	return nil
}

func (x *UserOpeningResponse) GetCounterAttestation() *CounterAttestation {
	if x != nil {
		return x.CounterAttestation
	}
	return nil
}

func (x *UserOpeningResponse) GetProof() *proto.G1 {
	if x != nil {
		return x.Proof
	}
	return nil
}

func (x *UserOpeningResponse) GetUsersBeforeMe() []int64 {
	if x != nil {
		return x.UsersBeforeMe
	}
	return nil
}

type UpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_key_curator_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_key_curator_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_key_curator_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Opening struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Opening []*proto.G1 `protobuf:"bytes,1,rep,name=opening,proto3" json:"opening,omitempty"`
}

func (x *Opening) Reset() {
	*x = Opening{}
	if protoimpl.UnsafeEnabled {
		mi := &file_key_curator_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Opening) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Opening) ProtoMessage() {}

func (x *Opening) ProtoReflect() protoreflect.Message {
	mi := &file_key_curator_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Opening.ProtoReflect.Descriptor instead.
func (*Opening) Descriptor() ([]byte, []int) {
	return file_key_curator_proto_rawDescGZIP(), []int{6}
}

func (x *Opening) GetOpening() []*proto.G1 {
	if x != nil {
		return x.Opening
	}
	return nil
}

type H1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	H1 []*proto.G1 `protobuf:"bytes,1,rep,name=h1,proto3" json:"h1,omitempty"`
}

func (x *H1) Reset() {
	*x = H1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_key_curator_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *H1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*H1) ProtoMessage() {}

func (x *H1) ProtoReflect() protoreflect.Message {
	mi := &file_key_curator_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use H1.ProtoReflect.Descriptor instead.
func (*H1) Descriptor() ([]byte, []int) {
	return file_key_curator_proto_rawDescGZIP(), []int{7}
}

func (x *H1) GetH1() []*proto.G1 {
	if x != nil {
		return x.H1
	}
	return nil
}

type H2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	H2 []*proto.G2 `protobuf:"bytes,1,rep,name=H2,proto3" json:"H2,omitempty"`
}

func (x *H2) Reset() {
	*x = H2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_key_curator_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *H2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*H2) ProtoMessage() {}

func (x *H2) ProtoReflect() protoreflect.Message {
	mi := &file_key_curator_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use H2.ProtoReflect.Descriptor instead.
func (*H2) Descriptor() ([]byte, []int) {
	return file_key_curator_proto_rawDescGZIP(), []int{8}
}

func (x *H2) GetH2() []*proto.G2 {
	if x != nil {
		return x.H2
	}
	return nil
}

type Commitments struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Commitments []*proto.G1 `protobuf:"bytes,1,rep,name=commitments,proto3" json:"commitments,omitempty"`
}

func (x *Commitments) Reset() {
	*x = Commitments{}
	if protoimpl.UnsafeEnabled {
		mi := &file_key_curator_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Commitments) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Commitments) ProtoMessage() {}

func (x *Commitments) ProtoReflect() protoreflect.Message {
	mi := &file_key_curator_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Commitments.ProtoReflect.Descriptor instead.
func (*Commitments) Descriptor() ([]byte, []int) {
	return file_key_curator_proto_rawDescGZIP(), []int{9}
}

func (x *Commitments) GetCommitments() []*proto.G1 {
	if x != nil {
		return x.Commitments
	}
	return nil
}

type AllUserOpenings struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AllOpenings []*Opening `protobuf:"bytes,1,rep,name=allOpenings,proto3" json:"allOpenings,omitempty"`
}

func (x *AllUserOpenings) Reset() {
	*x = AllUserOpenings{}
	if protoimpl.UnsafeEnabled {
		mi := &file_key_curator_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllUserOpenings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllUserOpenings) ProtoMessage() {}

func (x *AllUserOpenings) ProtoReflect() protoreflect.Message {
	mi := &file_key_curator_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllUserOpenings.ProtoReflect.Descriptor instead.
func (*AllUserOpenings) Descriptor() ([]byte, []int) {
	return file_key_curator_proto_rawDescGZIP(), []int{10}
}

func (x *AllUserOpenings) GetAllOpenings() []*Opening {
	if x != nil {
		return x.AllOpenings
	}
	return nil
}

type AllUpdatesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AllCommitments []*proto.G1          `protobuf:"bytes,1,rep,name=allCommitments,proto3" json:"allCommitments,omitempty"`
	AllOpenings    []*Opening           `protobuf:"bytes,2,rep,name=allOpenings,proto3" json:"allOpenings,omitempty"`
	History        []*RegistrationEvent `protobuf:"bytes,3,rep,name=history,proto3" json:"history,omitempty"`
}

func (x *AllUpdatesResponse) Reset() {
	*x = AllUpdatesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_key_curator_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllUpdatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllUpdatesResponse) ProtoMessage() {}

func (x *AllUpdatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_key_curator_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllUpdatesResponse.ProtoReflect.Descriptor instead.
func (*AllUpdatesResponse) Descriptor() ([]byte, []int) {
	return file_key_curator_proto_rawDescGZIP(), []int{11}
}

func (x *AllUpdatesResponse) GetAllCommitments() []*proto.G1 {
	if x != nil {
		return x.AllCommitments
	}
	return nil
}

func (x *AllUpdatesResponse) GetAllOpenings() []*Opening {
	if x != nil {
		return x.AllOpenings
	}
	return nil
}

func (x *AllUpdatesResponse) GetHistory() []*RegistrationEvent {
	if x != nil {
		return x.History
	}
	return nil
}

type RegistrationEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token              string              `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Ip                 string              `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Port               string              `protobuf:"bytes,3,opt,name=port,proto3" json:"port,omitempty"`
	Id                 int64               `protobuf:"varint,4,opt,name=id,proto3" json:"id,omitempty"`
	PublicKey          *proto.G1           `protobuf:"bytes,5,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	Xi                 []*proto.G1         `protobuf:"bytes,6,rep,name=xi,proto3" json:"xi,omitempty"`
	Request            *RegisterRequest    `protobuf:"bytes,7,opt,name=request,proto3" json:"request,omitempty"`
	Proof              *proto.G1           `protobuf:"bytes,8,opt,name=proof,proto3" json:"proof,omitempty"`
	CounterAttestation *CounterAttestation `protobuf:"bytes,9,opt,name=counterAttestation,proto3" json:"counterAttestation,omitempty"`
}

func (x *RegistrationEvent) Reset() {
	*x = RegistrationEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_key_curator_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegistrationEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationEvent) ProtoMessage() {}

func (x *RegistrationEvent) ProtoReflect() protoreflect.Message {
	mi := &file_key_curator_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationEvent.ProtoReflect.Descriptor instead.
func (*RegistrationEvent) Descriptor() ([]byte, []int) {
	return file_key_curator_proto_rawDescGZIP(), []int{12}
}

func (x *RegistrationEvent) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RegistrationEvent) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *RegistrationEvent) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *RegistrationEvent) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RegistrationEvent) GetPublicKey() *proto.G1 {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *RegistrationEvent) GetXi() []*proto.G1 {
	if x != nil {
		return x.Xi
	}
	return nil
}

func (x *RegistrationEvent) GetRequest() *RegisterRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *RegistrationEvent) GetProof() *proto.G1 {
	if x != nil {
		return x.Proof
	}
	return nil
}

func (x *RegistrationEvent) GetCounterAttestation() *CounterAttestation {
	if x != nil {
		return x.CounterAttestation
	}
	return nil
}

type CounterAttestation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Counter   uint64          `protobuf:"varint,1,opt,name=counter,proto3" json:"counter,omitempty"`
	MsgHash   []byte          `protobuf:"bytes,2,opt,name=msgHash,proto3" json:"msgHash,omitempty"`
	Signature *ECDSASignature `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *CounterAttestation) Reset() {
	*x = CounterAttestation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_key_curator_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CounterAttestation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CounterAttestation) ProtoMessage() {}

func (x *CounterAttestation) ProtoReflect() protoreflect.Message {
	mi := &file_key_curator_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CounterAttestation.ProtoReflect.Descriptor instead.
func (*CounterAttestation) Descriptor() ([]byte, []int) {
	return file_key_curator_proto_rawDescGZIP(), []int{13}
}

func (x *CounterAttestation) GetCounter() uint64 {
	if x != nil {
		return x.Counter
	}
	return 0
}

func (x *CounterAttestation) GetMsgHash() []byte {
	if x != nil {
		return x.MsgHash
	}
	return nil
}

func (x *CounterAttestation) GetSignature() *ECDSASignature {
	if x != nil {
		return x.Signature
	}
	return nil
}

type ECDSASignature struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	R []byte `protobuf:"bytes,1,opt,name=r,proto3" json:"r,omitempty"`
	S []byte `protobuf:"bytes,2,opt,name=s,proto3" json:"s,omitempty"`
}

func (x *ECDSASignature) Reset() {
	*x = ECDSASignature{}
	if protoimpl.UnsafeEnabled {
		mi := &file_key_curator_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ECDSASignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECDSASignature) ProtoMessage() {}

func (x *ECDSASignature) ProtoReflect() protoreflect.Message {
	mi := &file_key_curator_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECDSASignature.ProtoReflect.Descriptor instead.
func (*ECDSASignature) Descriptor() ([]byte, []int) {
	return file_key_curator_proto_rawDescGZIP(), []int{14}
}

func (x *ECDSASignature) GetR() []byte {
	if x != nil {
		return x.R
	}
	return nil
}

func (x *ECDSASignature) GetS() []byte {
	if x != nil {
		return x.S
	}
	return nil
}

type RegistrationNotification struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Id      int64  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RegistrationNotification) Reset() {
	*x = RegistrationNotification{}
	if protoimpl.UnsafeEnabled {
		mi := &file_key_curator_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegistrationNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationNotification) ProtoMessage() {}

func (x *RegistrationNotification) ProtoReflect() protoreflect.Message {
	mi := &file_key_curator_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationNotification.ProtoReflect.Descriptor instead.
func (*RegistrationNotification) Descriptor() ([]byte, []int) {
	return file_key_curator_proto_rawDescGZIP(), []int{15}
}

func (x *RegistrationNotification) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegistrationNotification) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_key_curator_proto protoreflect.FileDescriptor

var file_key_curator_proto_rawDesc = []byte{
	0x0a, 0x11, 0x6b, 0x65, 0x79, 0x5f, 0x63, 0x75, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x6b, 0x65, 0x79, 0x63, 0x75, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x1a,
	0x09, 0x72, 0x62, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x36, 0x0a, 0x0c, 0x52, 0x65, 0x61, 0x64, 0x79,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x65, 0x66, 0x69,
	0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x22,
	0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x3f, 0x0a, 0x14, 0x50, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x27, 0x0a, 0x02, 0x70, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x72,
	0x62, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x50,
	0x61, 0x72, 0x61, 0x6d, 0x73, 0x52, 0x02, 0x70, 0x70, 0x22, 0xa7, 0x01, 0x0a, 0x0f, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2b, 0x0a,
	0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0d, 0x2e, 0x72, 0x62, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x31, 0x52,
	0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x1d, 0x0a, 0x02, 0x78, 0x69,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x72, 0x62, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x47, 0x31, 0x52, 0x02, 0x78, 0x69, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72,
	0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x22, 0x88, 0x02, 0x0a, 0x13, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x70, 0x65, 0x6e,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x0a, 0x63,
	0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0d, 0x2e, 0x72, 0x62, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x31, 0x52, 0x0a,
	0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x27, 0x0a, 0x07, 0x6f, 0x70,
	0x65, 0x6e, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x72, 0x62,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x31, 0x52, 0x07, 0x6f, 0x70, 0x65, 0x6e,
	0x69, 0x6e, 0x67, 0x12, 0x4e, 0x0a, 0x12, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x41, 0x74,
	0x74, 0x65, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1e, 0x2e, 0x6b, 0x65, 0x79, 0x63, 0x75, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x65, 0x72, 0x41, 0x74, 0x74, 0x65, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x12, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x41, 0x74, 0x74, 0x65, 0x73, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x23, 0x0a, 0x05, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x72, 0x62, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47,
	0x31, 0x52, 0x05, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x12, 0x24, 0x0a, 0x0d, 0x75, 0x73, 0x65, 0x72,
	0x73, 0x42, 0x65, 0x66, 0x6f, 0x72, 0x65, 0x4d, 0x65, 0x18, 0x05, 0x20, 0x03, 0x28, 0x03, 0x52,
	0x0d, 0x75, 0x73, 0x65, 0x72, 0x73, 0x42, 0x65, 0x66, 0x6f, 0x72, 0x65, 0x4d, 0x65, 0x22, 0x1f,
	0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x32, 0x0a, 0x07, 0x4f, 0x70, 0x65, 0x6e, 0x69, 0x6e, 0x67, 0x12, 0x27, 0x0a, 0x07, 0x6f, 0x70,
	0x65, 0x6e, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x72, 0x62,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x31, 0x52, 0x07, 0x6f, 0x70, 0x65, 0x6e,
	0x69, 0x6e, 0x67, 0x22, 0x23, 0x0a, 0x02, 0x48, 0x31, 0x12, 0x1d, 0x0a, 0x02, 0x68, 0x31, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x72, 0x62, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x47, 0x31, 0x52, 0x02, 0x68, 0x31, 0x22, 0x23, 0x0a, 0x02, 0x48, 0x32, 0x12, 0x1d,
	0x0a, 0x02, 0x48, 0x32, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x72, 0x62, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x32, 0x52, 0x02, 0x48, 0x32, 0x22, 0x3e, 0x0a,
	0x0b, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x2f, 0x0a, 0x0b,
	0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x72, 0x62, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x31,
	0x52, 0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x48, 0x0a,
	0x0f, 0x41, 0x6c, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x70, 0x65, 0x6e, 0x69, 0x6e, 0x67, 0x73,
	0x12, 0x35, 0x0a, 0x0b, 0x61, 0x6c, 0x6c, 0x4f, 0x70, 0x65, 0x6e, 0x69, 0x6e, 0x67, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6b, 0x65, 0x79, 0x63, 0x75, 0x72, 0x61, 0x74,
	0x6f, 0x72, 0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x69, 0x6e, 0x67, 0x52, 0x0b, 0x61, 0x6c, 0x6c, 0x4f,
	0x70, 0x65, 0x6e, 0x69, 0x6e, 0x67, 0x73, 0x22, 0xbb, 0x01, 0x0a, 0x12, 0x41, 0x6c, 0x6c, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35,
	0x0a, 0x0e, 0x61, 0x6c, 0x6c, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x72, 0x62, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x47, 0x31, 0x52, 0x0e, 0x61, 0x6c, 0x6c, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74,
	0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x35, 0x0a, 0x0b, 0x61, 0x6c, 0x6c, 0x4f, 0x70, 0x65, 0x6e,
	0x69, 0x6e, 0x67, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6b, 0x65, 0x79,
	0x63, 0x75, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x69, 0x6e, 0x67, 0x52,
	0x0b, 0x61, 0x6c, 0x6c, 0x4f, 0x70, 0x65, 0x6e, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x37, 0x0a, 0x07,
	0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e,
	0x6b, 0x65, 0x79, 0x63, 0x75, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x07, 0x68, 0x69,
	0x73, 0x74, 0x6f, 0x72, 0x79, 0x22, 0xd5, 0x02, 0x0a, 0x11, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x70, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2b, 0x0a, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b,
	0x65, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x72, 0x62, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x31, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b,
	0x65, 0x79, 0x12, 0x1d, 0x0a, 0x02, 0x78, 0x69, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x72, 0x62, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x31, 0x52, 0x02, 0x78,
	0x69, 0x12, 0x35, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6b, 0x65, 0x79, 0x63, 0x75, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52,
	0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x05, 0x70, 0x72, 0x6f, 0x6f,
	0x66, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x72, 0x62, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x31, 0x52, 0x05, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x12, 0x4e, 0x0a,
	0x12, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x41, 0x74, 0x74, 0x65, 0x73, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x6b, 0x65, 0x79, 0x63,
	0x75, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x41, 0x74,
	0x74, 0x65, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x12, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x65, 0x72, 0x41, 0x74, 0x74, 0x65, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x82, 0x01,
	0x0a, 0x12, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x41, 0x74, 0x74, 0x65, 0x73, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x73, 0x67, 0x48, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x07, 0x6d, 0x73, 0x67, 0x48, 0x61, 0x73, 0x68, 0x12, 0x38, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6b, 0x65,
	0x79, 0x63, 0x75, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x45, 0x43, 0x44, 0x53, 0x41, 0x53, 0x69,
	0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75,
	0x72, 0x65, 0x22, 0x2c, 0x0a, 0x0e, 0x45, 0x43, 0x44, 0x53, 0x41, 0x53, 0x69, 0x67, 0x6e, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x12, 0x0c, 0x0a, 0x01, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x01, 0x72, 0x12, 0x0c, 0x0a, 0x01, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x01, 0x73,
	0x22, 0x44, 0x0a, 0x18, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x32, 0xe1, 0x03, 0x0a, 0x0a, 0x4b, 0x65, 0x79, 0x43, 0x75,
	0x72, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x4b, 0x0a, 0x0b, 0x46, 0x65, 0x74, 0x63, 0x68, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x12, 0x19, 0x2e, 0x6b, 0x65, 0x79, 0x63, 0x75, 0x72, 0x61, 0x74, 0x6f,
	0x72, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1f, 0x2e, 0x6b, 0x65, 0x79, 0x63, 0x75, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x4f, 0x70, 0x65, 0x6e, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x4b, 0x0a, 0x0f, 0x46, 0x65, 0x74, 0x63, 0x68, 0x41, 0x6c, 0x6c, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x1e, 0x2e,
	0x6b, 0x65, 0x79, 0x63, 0x75, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x41, 0x6c, 0x6c, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x4f, 0x0a, 0x11, 0x46, 0x65, 0x74, 0x63, 0x68, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x50, 0x61,
	0x72, 0x61, 0x6d, 0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x20, 0x2e, 0x6b,
	0x65, 0x79, 0x63, 0x75, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x4e, 0x0a, 0x0c, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72,
	0x12, 0x1b, 0x2e, 0x6b, 0x65, 0x79, 0x63, 0x75, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e,
	0x6b, 0x65, 0x79, 0x63, 0x75, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x4f,
	0x70, 0x65, 0x6e, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x3f, 0x0a, 0x09, 0x4d, 0x61, 0x72, 0x6b, 0x52, 0x65, 0x61, 0x64, 0x79, 0x12, 0x18, 0x2e,
	0x6b, 0x65, 0x79, 0x63, 0x75, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x79,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22,
	0x00, 0x12, 0x57, 0x0a, 0x13, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x1a, 0x24, 0x2e, 0x6b, 0x65, 0x79, 0x63, 0x75, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x00, 0x30, 0x01, 0x42, 0x35, 0x5a, 0x33, 0x69, 0x73,
	0x74, 0x69, 0x6f, 0x2e, 0x69, 0x6f, 0x2f, 0x69, 0x73, 0x74, 0x69, 0x6f, 0x2f, 0x73, 0x65, 0x63,
	0x75, 0x72, 0x69, 0x74, 0x79, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x6b, 0x65, 0x79, 0x2d, 0x63, 0x75,
	0x72, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x6b, 0x65, 0x79, 0x2d, 0x63, 0x75, 0x72, 0x61, 0x74, 0x6f,
	0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_key_curator_proto_rawDescOnce sync.Once
	file_key_curator_proto_rawDescData = file_key_curator_proto_rawDesc
)

func file_key_curator_proto_rawDescGZIP() []byte {
	file_key_curator_proto_rawDescOnce.Do(func() {
		file_key_curator_proto_rawDescData = protoimpl.X.CompressGZIP(file_key_curator_proto_rawDescData)
	})
	return file_key_curator_proto_rawDescData
}

var file_key_curator_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_key_curator_proto_goTypes = []interface{}{
	(*ReadyRequest)(nil),             // 0: keycurator.ReadyRequest
	(*Empty)(nil),                    // 1: keycurator.Empty
	(*PublicParamsResponse)(nil),     // 2: keycurator.PublicParamsResponse
	(*RegisterRequest)(nil),          // 3: keycurator.RegisterRequest
	(*UserOpeningResponse)(nil),      // 4: keycurator.UserOpeningResponse
	(*UpdateRequest)(nil),            // 5: keycurator.UpdateRequest
	(*Opening)(nil),                  // 6: keycurator.Opening
	(*H1)(nil),                       // 7: keycurator.H1
	(*H2)(nil),                       // 8: keycurator.H2
	(*Commitments)(nil),              // 9: keycurator.Commitments
	(*AllUserOpenings)(nil),          // 10: keycurator.AllUserOpenings
	(*AllUpdatesResponse)(nil),       // 11: keycurator.AllUpdatesResponse
	(*RegistrationEvent)(nil),        // 12: keycurator.RegistrationEvent
	(*CounterAttestation)(nil),       // 13: keycurator.CounterAttestation
	(*ECDSASignature)(nil),           // 14: keycurator.ECDSASignature
	(*RegistrationNotification)(nil), // 15: keycurator.RegistrationNotification
	(*proto.PublicParams)(nil),       // 16: rbe.proto.PublicParams
	(*proto.G1)(nil),                 // 17: rbe.proto.G1
	(*proto.G2)(nil),                 // 18: rbe.proto.G2
	(*emptypb.Empty)(nil),            // 19: google.protobuf.Empty
}
var file_key_curator_proto_depIdxs = []int32{
	16, // 0: keycurator.PublicParamsResponse.pp:type_name -> rbe.proto.PublicParams
	17, // 1: keycurator.RegisterRequest.publicKey:type_name -> rbe.proto.G1
	17, // 2: keycurator.RegisterRequest.xi:type_name -> rbe.proto.G1
	17, // 3: keycurator.UserOpeningResponse.commitment:type_name -> rbe.proto.G1
	17, // 4: keycurator.UserOpeningResponse.opening:type_name -> rbe.proto.G1
	13, // 5: keycurator.UserOpeningResponse.counterAttestation:type_name -> keycurator.CounterAttestation
	17, // 6: keycurator.UserOpeningResponse.proof:type_name -> rbe.proto.G1
	17, // 7: keycurator.Opening.opening:type_name -> rbe.proto.G1
	17, // 8: keycurator.H1.h1:type_name -> rbe.proto.G1
	18, // 9: keycurator.H2.H2:type_name -> rbe.proto.G2
	17, // 10: keycurator.Commitments.commitments:type_name -> rbe.proto.G1
	6,  // 11: keycurator.AllUserOpenings.allOpenings:type_name -> keycurator.Opening
	17, // 12: keycurator.AllUpdatesResponse.allCommitments:type_name -> rbe.proto.G1
	6,  // 13: keycurator.AllUpdatesResponse.allOpenings:type_name -> keycurator.Opening
	12, // 14: keycurator.AllUpdatesResponse.history:type_name -> keycurator.RegistrationEvent
	17, // 15: keycurator.RegistrationEvent.publicKey:type_name -> rbe.proto.G1
	17, // 16: keycurator.RegistrationEvent.xi:type_name -> rbe.proto.G1
	3,  // 17: keycurator.RegistrationEvent.request:type_name -> keycurator.RegisterRequest
	17, // 18: keycurator.RegistrationEvent.proof:type_name -> rbe.proto.G1
	13, // 19: keycurator.RegistrationEvent.counterAttestation:type_name -> keycurator.CounterAttestation
	14, // 20: keycurator.CounterAttestation.signature:type_name -> keycurator.ECDSASignature
	5,  // 21: keycurator.KeyCurator.FetchUpdate:input_type -> keycurator.UpdateRequest
	19, // 22: keycurator.KeyCurator.FetchAllUpdates:input_type -> google.protobuf.Empty
	19, // 23: keycurator.KeyCurator.FetchPublicParams:input_type -> google.protobuf.Empty
	3,  // 24: keycurator.KeyCurator.RegisterUser:input_type -> keycurator.RegisterRequest
	0,  // 25: keycurator.KeyCurator.MarkReady:input_type -> keycurator.ReadyRequest
	19, // 26: keycurator.KeyCurator.StreamRegistrations:input_type -> google.protobuf.Empty
	4,  // 27: keycurator.KeyCurator.FetchUpdate:output_type -> keycurator.UserOpeningResponse
	11, // 28: keycurator.KeyCurator.FetchAllUpdates:output_type -> keycurator.AllUpdatesResponse
	2,  // 29: keycurator.KeyCurator.FetchPublicParams:output_type -> keycurator.PublicParamsResponse
	4,  // 30: keycurator.KeyCurator.RegisterUser:output_type -> keycurator.UserOpeningResponse
	19, // 31: keycurator.KeyCurator.MarkReady:output_type -> google.protobuf.Empty
	15, // 32: keycurator.KeyCurator.StreamRegistrations:output_type -> keycurator.RegistrationNotification
	27, // [27:33] is the sub-list for method output_type
	21, // [21:27] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_key_curator_proto_init() }
func file_key_curator_proto_init() {
	if File_key_curator_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_key_curator_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_key_curator_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_key_curator_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublicParamsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_key_curator_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_key_curator_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserOpeningResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_key_curator_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_key_curator_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Opening); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_key_curator_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*H1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_key_curator_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*H2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_key_curator_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Commitments); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_key_curator_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllUserOpenings); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_key_curator_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllUpdatesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_key_curator_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegistrationEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_key_curator_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CounterAttestation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_key_curator_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ECDSASignature); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_key_curator_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegistrationNotification); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_key_curator_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_key_curator_proto_goTypes,
		DependencyIndexes: file_key_curator_proto_depIdxs,
		MessageInfos:      file_key_curator_proto_msgTypes,
	}.Build()
	File_key_curator_proto = out.File
	file_key_curator_proto_rawDesc = nil
	file_key_curator_proto_goTypes = nil
	file_key_curator_proto_depIdxs = nil
}
