// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.28.3
// source: key-curator/key_curator.proto

package key_curator

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lambda uint32 `protobuf:"varint,1,opt,name=lambda,proto3" json:"lambda,omitempty"`
	N      uint32 `protobuf:"varint,2,opt,name=N,proto3" json:"N,omitempty"`
}

func (x *SetupRequest) Reset() {
	*x = SetupRequest{}
	mi := &file_key_curator_key_curator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupRequest) ProtoMessage() {}

func (x *SetupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_key_curator_key_curator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupRequest.ProtoReflect.Descriptor instead.
func (*SetupRequest) Descriptor() ([]byte, []int) {
	return file_key_curator_key_curator_proto_rawDescGZIP(), []int{0}
}

func (x *SetupRequest) GetLambda() uint32 {
	if x != nil {
		return x.Lambda
	}
	return 0
}

func (x *SetupRequest) GetN() uint32 {
	if x != nil {
		return x.N
	}
	return 0
}

type SetupResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Crs string `protobuf:"bytes,1,opt,name=crs,proto3" json:"crs,omitempty"`
}

func (x *SetupResponse) Reset() {
	*x = SetupResponse{}
	mi := &file_key_curator_key_curator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupResponse) ProtoMessage() {}

func (x *SetupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_key_curator_key_curator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupResponse.ProtoReflect.Descriptor instead.
func (*SetupResponse) Descriptor() ([]byte, []int) {
	return file_key_curator_key_curator_proto_rawDescGZIP(), []int{1}
}

func (x *SetupResponse) GetCrs() string {
	if x != nil {
		return x.Crs
	}
	return ""
}

type RegisterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Crs string `protobuf:"bytes,1,opt,name=crs,proto3" json:"crs,omitempty"`
	Pp  string `protobuf:"bytes,2,opt,name=pp,proto3" json:"pp,omitempty"`
	Id  string `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Pk  string `protobuf:"bytes,4,opt,name=pk,proto3" json:"pk,omitempty"`
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_key_curator_key_curator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_key_curator_key_curator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_key_curator_key_curator_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterRequest) GetCrs() string {
	if x != nil {
		return x.Crs
	}
	return ""
}

func (x *RegisterRequest) GetPp() string {
	if x != nil {
		return x.Pp
	}
	return ""
}

func (x *RegisterRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RegisterRequest) GetPk() string {
	if x != nil {
		return x.Pk
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pp string `protobuf:"bytes,1,opt,name=pp,proto3" json:"pp,omitempty"`
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_key_curator_key_curator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_key_curator_key_curator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_key_curator_key_curator_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterResponse) GetPp() string {
	if x != nil {
		return x.Pp
	}
	return ""
}

type UpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pp string `protobuf:"bytes,2,opt,name=pp,proto3" json:"pp,omitempty"`
	Id string `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_key_curator_key_curator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_key_curator_key_curator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_key_curator_key_curator_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateRequest) GetPp() string {
	if x != nil {
		return x.Pp
	}
	return ""
}

func (x *UpdateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	U string `protobuf:"bytes,1,opt,name=u,proto3" json:"u,omitempty"`
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_key_curator_key_curator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_key_curator_key_curator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_key_curator_key_curator_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateResponse) GetU() string {
	if x != nil {
		return x.U
	}
	return ""
}

var File_key_curator_key_curator_proto protoreflect.FileDescriptor

var file_key_curator_key_curator_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x6b, 0x65, 0x79, 0x2d, 0x63, 0x75, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x6b, 0x65,
	0x79, 0x5f, 0x63, 0x75, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0a, 0x6b, 0x65, 0x79, 0x63, 0x75, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x22, 0x34, 0x0a, 0x0c, 0x53,
	0x65, 0x74, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6c,
	0x61, 0x6d, 0x62, 0x64, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x6c, 0x61, 0x6d,
	0x62, 0x64, 0x61, 0x12, 0x0c, 0x0a, 0x01, 0x4e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x01,
	0x4e, 0x22, 0x21, 0x0a, 0x0d, 0x53, 0x65, 0x74, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x72, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x63, 0x72, 0x73, 0x22, 0x53, 0x0a, 0x0f, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x72, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63, 0x72, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x70, 0x70, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x70, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x70, 0x6b, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x70, 0x6b, 0x22, 0x22, 0x0a, 0x10, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x70, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x70, 0x70, 0x22, 0x2f, 0x0a,
	0x0d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x70, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x70, 0x70, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x1e,
	0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x0c, 0x0a, 0x01, 0x75, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x75, 0x32, 0xdc,
	0x01, 0x0a, 0x0a, 0x4b, 0x65, 0x79, 0x43, 0x75, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x3e, 0x0a,
	0x05, 0x53, 0x65, 0x74, 0x75, 0x70, 0x12, 0x18, 0x2e, 0x6b, 0x65, 0x79, 0x63, 0x75, 0x72, 0x61,
	0x74, 0x6f, 0x72, 0x2e, 0x53, 0x65, 0x74, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x19, 0x2e, 0x6b, 0x65, 0x79, 0x63, 0x75, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x53, 0x65,
	0x74, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4b, 0x0a,
	0x0c, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x12, 0x1b, 0x2e,
	0x6b, 0x65, 0x79, 0x63, 0x75, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x6b, 0x65, 0x79,
	0x63, 0x75, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x41, 0x0a, 0x06, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x12, 0x19, 0x2e, 0x6b, 0x65, 0x79, 0x63, 0x75, 0x72, 0x61, 0x74, 0x6f,
	0x72, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1a, 0x2e, 0x6b, 0x65, 0x79, 0x63, 0x75, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x35, 0x5a,
	0x33, 0x69, 0x73, 0x74, 0x69, 0x6f, 0x2e, 0x69, 0x6f, 0x2f, 0x69, 0x73, 0x74, 0x69, 0x6f, 0x2f,
	0x73, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x6b, 0x65, 0x79,
	0x2d, 0x63, 0x75, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x6b, 0x65, 0x79, 0x2d, 0x63, 0x75, 0x72,
	0x61, 0x74, 0x6f, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_key_curator_key_curator_proto_rawDescOnce sync.Once
	file_key_curator_key_curator_proto_rawDescData = file_key_curator_key_curator_proto_rawDesc
)

func file_key_curator_key_curator_proto_rawDescGZIP() []byte {
	file_key_curator_key_curator_proto_rawDescOnce.Do(func() {
		file_key_curator_key_curator_proto_rawDescData = protoimpl.X.CompressGZIP(file_key_curator_key_curator_proto_rawDescData)
	})
	return file_key_curator_key_curator_proto_rawDescData
}

var file_key_curator_key_curator_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_key_curator_key_curator_proto_goTypes = []any{
	(*SetupRequest)(nil),     // 0: keycurator.SetupRequest
	(*SetupResponse)(nil),    // 1: keycurator.SetupResponse
	(*RegisterRequest)(nil),  // 2: keycurator.RegisterRequest
	(*RegisterResponse)(nil), // 3: keycurator.RegisterResponse
	(*UpdateRequest)(nil),    // 4: keycurator.UpdateRequest
	(*UpdateResponse)(nil),   // 5: keycurator.UpdateResponse
}
var file_key_curator_key_curator_proto_depIdxs = []int32{
	0, // 0: keycurator.KeyCurator.Setup:input_type -> keycurator.SetupRequest
	2, // 1: keycurator.KeyCurator.RegisterUser:input_type -> keycurator.RegisterRequest
	4, // 2: keycurator.KeyCurator.Update:input_type -> keycurator.UpdateRequest
	1, // 3: keycurator.KeyCurator.Setup:output_type -> keycurator.SetupResponse
	3, // 4: keycurator.KeyCurator.RegisterUser:output_type -> keycurator.RegisterResponse
	5, // 5: keycurator.KeyCurator.Update:output_type -> keycurator.UpdateResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_key_curator_key_curator_proto_init() }
func file_key_curator_key_curator_proto_init() {
	if File_key_curator_key_curator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_key_curator_key_curator_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_key_curator_key_curator_proto_goTypes,
		DependencyIndexes: file_key_curator_key_curator_proto_depIdxs,
		MessageInfos:      file_key_curator_key_curator_proto_msgTypes,
	}.Build()
	File_key_curator_key_curator_proto = out.File
	file_key_curator_key_curator_proto_rawDesc = nil
	file_key_curator_key_curator_proto_goTypes = nil
	file_key_curator_key_curator_proto_depIdxs = nil
}
