apiVersion: v1
kind: Service
metadata:
  name: micro-benchmark-1
  labels:
    app: micro-benchmark-1
    service: micro-benchmark-1
spec:
  ports:
  - port: 5000
    name: http
  selector:
    app: micro-benchmark-1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-benchmark-1-v1
  labels:
    app: micro-benchmark-1
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: micro-benchmark-1
      version: v1
  template:
    metadata:
      labels:
        app: micro-benchmark-1
        version: v1
    spec:
      containers:
      - name: helloworld
        image: docker.io/istio/examples-helloworld-v1:1.0
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000